version: '3.9'

services:
  whatsapp:
    image: openwa/wa-automate
    restart: always
    ports:
      - 3339:3339
    environment:
      - WA_PORT=3339
  
  vagas:
    image: node:16
    container_name: vagas
    restart: always
    ports:
      - 3334:3334
    volumes:
      - ./api/vagas:/usr/app/vagas
    working_dir: /usr/app/vagas
    command: bash -c "npm install && npm start"

  gateway:
    image: node:16
    container_name: gateway
    restart: always
    ports:
      - 7777:7777
    volumes:
      - ./api/gateway:/usr/app/gateway
    working_dir: /usr/app/gateway
    command: bash -c "npm install && npm start"